<?php

namespace Database\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version20160308144531 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE lectures ADD year SMALLINT NOT NULL');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=1');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=2');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=3');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=4');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=5');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=6');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=7');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=8');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=9');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=10');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=11');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=12');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=13');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=14');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=15');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=16');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=17');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=18');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=19');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=20');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=21');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=22');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=23');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=24');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=25');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=26');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=27');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=28');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=29');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=30');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=31');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=32');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=33');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=34');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=35');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=36');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=37');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=38');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=39');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=40');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=41');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=42');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=43');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=44');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=45');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=46');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=47');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=48');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=49');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=50');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=51');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=52');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=53');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=54');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=55');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=56');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=57');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=58');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=59');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=60');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=61');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=62');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=63');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=64');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=65');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=66');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=67');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=68');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=69');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=70');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=71');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=72');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=73');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=74');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=75');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=76');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=77');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=78');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=79');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=80');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=81');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=82');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=83');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=84');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=85');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=86');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=87');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=88');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=89');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=90');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=91');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=92');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=93');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=94');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=95');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=96');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=97');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=98');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=99');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=100');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=101');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=102');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=103');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=104');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=105');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=106');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=107');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=108');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=109');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=110');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=111');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=112');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=113');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=114');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=115');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=116');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=117');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=118');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=119');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=120');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=121');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=122');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=123');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=124');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=125');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=126');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=127');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=128');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=129');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=130');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=131');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=132');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=133');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=134');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=135');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=136');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=137');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=138');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=139');
        $this->addSql('UPDATE lectures SET year=2015 WHERE id=140');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=141');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=142');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=143');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=144');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=145');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=146');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=147');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=148');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=149');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=150');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=151');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=152');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=153');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=154');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=155');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=156');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=157');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=158');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=159');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=160');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=161');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=162');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=163');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=164');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=165');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=166');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=167');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=168');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=169');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=170');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=171');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=172');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=173');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=174');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=175');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=176');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=177');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=178');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=179');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=180');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=181');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=182');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=183');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=184');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=185');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=186');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=187');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=188');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=189');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=190');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=191');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=192');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=193');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=194');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=195');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=196');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=197');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=198');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=199');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=200');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=201');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=202');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=203');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=204');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=205');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=206');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=207');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=208');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=209');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=210');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=211');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=212');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=213');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=214');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=215');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=216');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=217');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=218');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=219');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=220');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=221');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=222');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=223');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=224');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=225');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=226');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=227');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=228');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=229');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=230');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=231');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=232');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=233');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=234');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=235');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=236');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=237');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=238');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=239');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=240');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=241');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=242');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=243');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=244');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=245');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=246');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=247');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=248');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=249');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=250');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=251');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=252');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=253');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=254');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=255');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=256');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=257');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=258');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=259');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=260');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=261');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=262');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=263');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=264');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=265');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=266');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=267');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=268');
        $this->addSql('UPDATE lectures SET year=2016 WHERE id=269');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE lectures DROP year');
    }
}
