<?php

namespace Database\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version20151229165435 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE events CHANGE starts_at starts_at TIME NOT NULL, CHANGE ends_at ends_at TIME NOT NULL');
        $this->addSql('ALTER TABLE lectures CHANGE starts_at starts_at INT NOT NULL, CHANGE ends_at ends_at INT NOT NULL');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'1\', \'73\', \'62\', \'2\', \'Вежбе\', \'389700\', \'399600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'2\', \'73\', \'62\', \'2\', \'Предавања\', \'44100\', \'54000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'3\', \'73\', \'64\', \'3\', \'Предавања\', \'216900\', \'226800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'4\', \'73\', \'64\', \'3\', \'Вежбе\', \'130500\', \'140400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'5\', \'14\', \'60\', \'1\', \'Вежбе\', \'242100\', \'248400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'6\', \'14\', \'60\', \'1\', \'Вежбе\', \'234900\', \'241200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'7\', \'14\', \'35\', \'1\', \'Предавања\', \'141300\', \'147600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'8\', \'11\', \'61\', \'4\', \'Вежбе\', \'148500\', \'154800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'9\', \'11\', \'61\', \'5\', \'Вежбе\', \'69300\', \'75600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'10\', \'11\', \'66\', \'4\', \'Вежбе\', \'407700\', \'414000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'11\', \'11\', \'66\', \'2\', \'Вежбе\', \'234900\', \'241200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'12\', \'11\', \'24\', \'1\', \'Предавања\', \'130500\', \'140400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'13\', \'11\', \'12\', \'1\', \'Предавања\', \'224100\', \'234000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'14\', \'50\', \'37\', \'6\', \'Предавања\', \'407700\', \'414000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'15\', \'50\', \'55\', \'2\', \'Вежбе\', \'227700\', \'234000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'16\', \'64\', \'10\', \'7\', \'Предавања\', \'382500\', \'392400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'17\', \'64\', \'55\', \'7\', \'Вежбе\', \'216900\', \'226800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'18\', \'92\', \'67\', \'5\', \'Предавања\', \'324900\', \'334800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'19\', \'92\', \'67\', \'5\', \'Вежбе\', \'152100\', \'162000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'20\', \'2\', \'60\', \'1\', \'Вежбе\', \'62100\', \'68400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'21\', \'2\', \'60\', \'1\', \'Вежбе\', \'404100\', \'410400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'22\', \'2\', \'60\', \'1\', \'Вежбе\', \'47700\', \'54000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'23\', \'2\', \'35\', \'6\', \'Предавања\', \'220500\', \'230400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'24\', \'2\', \'35\', \'1\', \'Предавања\', \'393300\', \'403200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'25\', \'78\', \'16\', \'6\', \'Предавања\', \'299700\', \'306000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'26\', \'78\', \'51\', \'2\', \'Вежбе\', \'378900\', \'388800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'27\', \'78\', \'51\', \'3\', \'Вежбе\', \'389700\', \'399600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'28\', \'12\', \'13\', \'6\', \'Предавања\', \'306900\', \'313200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'29\', \'12\', \'13\', \'6\', \'Предавања\', \'314100\', \'320400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'30\', \'12\', \'57\', \'4\', \'Вежбе\', \'393300\', \'399600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'31\', \'12\', \'57\', \'4\', \'Вежбе\', \'378900\', \'385200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'32\', \'12\', \'57\', \'4\', \'Вежбе\', \'386100\', \'392400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'33\', \'83\', \'70\', \'6\', \'Предавања\', \'386100\', \'392400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'34\', \'83\', \'70\', \'1\', \'Вежбе\', \'40500\', \'46800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'35\', \'4\', \'70\', \'1\', \'Предавања\', \'303300\', \'309600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'36\', \'4\', \'70\', \'1\', \'Предавања\', \'54900\', \'61200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'37\', \'4\', \'70\', \'1\', \'Предавања\', \'378900\', \'385200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'38\', \'4\', \'70\', \'6\', \'Предавања\', \'206100\', \'212400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'39\', \'31\', \'63\', \'3\', \'Вежбе\', \'36900\', \'43200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'40\', \'31\', \'22\', \'9\', \'Предавања\', \'407700\', \'414000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'41\', \'21\', \'71\', \'2\', \'Вежбе\', \'155700\', \'162000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'42\', \'21\', \'12\', \'9\', \'Предавања\', \'69300\', \'75600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'43\', \'101\', \'62\', \'5\', \'Предавања и Вежбе\', \'33300\', \'43200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'44\', \'101\', \'62\', \'5\', \'Предавања и Вежбе\', \'126900\', \'136800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'45\', \'82\', \'51\', \'2\', \'Вежбе\', \'206100\', \'216000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'46\', \'82\', \'51\', \'2\', \'Вежбе\', \'216900\', \'226800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'47\', \'82\', \'19\', \'1\', \'Предавања\', \'119700\', \'129600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'48\', \'39\', \'72\', \'4\', \'Вежбе\', \'242100\', \'248400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'49\', \'39\', \'21\', \'6\', \'Предавања\', \'234900\', \'241200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'50\', \'13\', \'73\', \'5\', \'Вежбе\', \'234900\', \'241200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'51\', \'13\', \'73\', \'5\', \'Вежбе\', \'242100\', \'248400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'52\', \'13\', \'73\', \'4\', \'Вежбе\', \'62100\', \'68400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'53\', \'13\', \'73\', \'5\', \'Вежбе\', \'386100\', \'392400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'54\', \'13\', \'73\', \'5\', \'Вежбе\', \'378900\', \'385200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'55\', \'13\', \'22\', \'6\', \'Предавања\', \'69300\', \'75600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'56\', \'13\', \'22\', \'1\', \'Предавања\', \'155700\', \'162000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'57\', \'13\', \'22\', \'6\', \'Предавања\', \'62100\', \'68400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'58\', \'88\', \'51\', \'5\', \'Блок настава\', \'465300\', \'471600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'59\', \'88\', \'19\', \'9\', \'Предавања\', \'137700\', \'144000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'60\', \'102\', \'10\', \'6\', \'Предавања\', \'393300\', \'399600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'61\', \'102\', \'55\', \'4\', \'Вежбе\', \'141300\', \'147600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'62\', \'102\', \'55\', \'4\', \'Вежбе\', \'54900\', \'61200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'63\', \'24\', \'63\', \'4\', \'Вежбе\', \'317700\', \'324000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'64\', \'24\', \'12\', \'1\', \'Предавања\', \'148500\', \'154800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'65\', \'1\', \'74\', \'1\', \'Предавања\', \'310500\', \'320400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'66\', \'1\', \'74\', \'1\', \'Предавања\', \'321300\', \'331200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'67\', \'1\', \'74\', \'6\', \'Предавања\', \'33300\', \'43200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'68\', \'1\', \'60\', \'1\', \'Вежбе\', \'69300\', \'75600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'69\', \'1\', \'60\', \'1\', \'Вежбе\', \'411300\', \'417600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'70\', \'1\', \'60\', \'1\', \'Вежбе\', \'386100\', \'392400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'71\', \'69\', \'52\', \'8\', \'Предавања\', \'119700\', \'126000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'72\', \'69\', \'65\', \'3\', \'Вежбе\', \'299700\', \'306000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'73\', \'41\', \'63\', \'4\', \'Вежбе\', \'130500\', \'140400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'74\', \'41\', \'21\', \'6\', \'Предавања\', \'44100\', \'54000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'75\', \'43\', \'54\', \'5\', \'Вежбе\', \'206100\', \'216000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'76\', \'43\', \'6\', \'4\', \'Предавања\', \'292500\', \'302400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'77\', \'75\', \'47\', \'4\', \'Вежбе\', \'306900\', \'316800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'78\', \'75\', \'47\', \'6\', \'Предавања\', \'119700\', \'129600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'79\', \'75\', \'47\', \'2\', \'Вежбе\', \'54900\', \'64800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'80\', \'47\', \'20\', \'9\', \'Предавања\', \'148500\', \'154800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'81\', \'47\', \'20\', \'9\', \'Вежбе\', \'155700\', \'162000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'82\', \'80\', \'64\', \'2\', \'Вежбе\', \'296100\', \'306000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'83\', \'80\', \'64\', \'6\', \'Предавања\', \'378900\', \'385200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'84\', \'80\', \'64\', \'2\', \'Вежбе\', \'314100\', \'324000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'85\', \'5\', \'75\', \'3\', \'Вежбе\', \'54900\', \'61200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'86\', \'5\', \'75\', \'3\', \'Вежбе\', \'306900\', \'313200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'87\', \'5\', \'75\', \'3\', \'Вежбе\', \'123300\', \'129600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'88\', \'5\', \'75\', \'3\', \'Вежбе\', \'141300\', \'147600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'89\', \'5\', \'75\', \'3\', \'Вежбе\', \'314100\', \'320400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'90\', \'5\', \'75\', \'3\', \'Вежбе\', \'44100\', \'50400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'91\', \'58\', \'52\', \'8\', \'Предавања\', \'126900\', \'133200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'92\', \'58\', \'65\', \'3\', \'Вежбе\', \'62100\', \'68400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'93\', \'76\', \'51\', \'4\', \'Предавања\', \'33300\', \'39600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'94\', \'76\', \'51\', \'4\', \'Вежбе\', \'40500\', \'46800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'95\', \'26\', \'2\', \'9\', \'Предавања\', \'227700\', \'234000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'96\', \'26\', \'53\', \'4\', \'Вежбе\', \'220500\', \'226800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'97\', \'19\', \'68\', \'3\', \'Вежбе\', \'472500\', \'478800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'98\', \'19\', \'21\', \'3\', \'Предавања\', \'465300\', \'471600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'99\', \'100\', \'13\', \'6\', \'Предавања\', \'292500\', \'298800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'100\', \'100\', \'13\', \'5\', \'Вежбе\', \'299700\', \'306000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'101\', \'55\', \'9\', \'7\', \'Предавања\', \'299700\', \'309600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'102\', \'55\', \'52\', \'2\', \'Вежбе\', \'141300\', \'151200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'103\', \'104\', \'19\', \'3\', \'Предавања\', \'227700\', \'237600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'104\', \'49\', \'9\', \'9\', \'Предавања\', \'310500\', \'320400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'105\', \'49\', \'47\', \'2\', \'Вежбе\', \'400500\', \'406800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'106\', \'67\', \'65\', \'2\', \'Вежбе\', \'306900\', \'313200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'107\', \'67\', \'77\', \'2\', \'Предавања\', \'69300\', \'75600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'108\', \'40\', \'16\', \'5\', \'Предавања\', \'306900\', \'313200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'109\', \'40\', \'78\', \'4\', \'Вежбе\', \'69300\', \'75600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'110\', \'91\', \'16\', \'5\', \'Предавања и Вежбе\', \'51300\', \'61200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'111\', \'91\', \'16\', \'5\', \'Предавања и Вежбе\', \'224100\', \'234000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'112\', \'103\', \'79\', \'3\', \'Практикум\', \'400500\', \'410400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'113\', \'105\', \'63\', \'5\', \'Вежбе\', \'400500\', \'406800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'114\', \'105\', \'12\', \'6\', \'Предавања\', \'54900\', \'61200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'115\', \'42\', \'53\', \'6\', \'Предавања\', \'213300\', \'219600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'116\', \'42\', \'53\', \'4\', \'Вежбе\', \'206100\', \'212400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'117\', \'89\', \'62\', \'3\', \'Вежбе\', \'378900\', \'388800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'118\', \'89\', \'62\', \'3\', \'Предавања\', \'206100\', \'216000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'119\', \'3\', \'14\', \'6\', \'Предавања\', \'130500\', \'136800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'120\', \'3\', \'72\', \'4\', \'Практикум\', \'234900\', \'241200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'121\', \'3\', \'72\', \'5\', \'Практикум\', \'314100\', \'320400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'122\', \'3\', \'72\', \'5\', \'Практикум\', \'144900\', \'151200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'123\', \'3\', \'66\', \'4\', \'Практикум\', \'47700\', \'54000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'124\', \'3\', \'66\', \'4\', \'Практикум\', \'213300\', \'219600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'125\', \'3\', \'66\', \'4\', \'Практикум\', \'472500\', \'478800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'126\', \'3\', \'56\', \'4\', \'Вежбе\', \'324900\', \'331200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'127\', \'3\', \'56\', \'5\', \'Вежбе\', \'62100\', \'68400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'128\', \'3\', \'54\', \'4\', \'Вежбе\', \'123300\', \'129600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'129\', \'3\', \'54\', \'5\', \'Вежбе\', \'44100\', \'50400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'130\', \'3\', \'54\', \'5\', \'Вежбе\', \'216900\', \'223200\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'131\', \'3\', \'54\', \'4\', \'Вежбе\', \'465300\', \'471600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'132\', \'3\', \'12\', \'1\', \'Предавања\', \'213300\', \'219600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'133\', \'3\', \'12\', \'1\', \'Предавања\', \'206100\', \'212400\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'134\', \'87\', \'20\', \'9\', \'Предавања\', \'400500\', \'406800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'135\', \'87\', \'69\', \'5\', \'Вежбе\', \'393300\', \'399600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'136\', \'68\', \'52\', \'2\', \'Предавања\', \'407700\', \'414000\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'137\', \'68\', \'65\', \'3\', \'Вежбе\', \'292500\', \'298800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'138\', \'81\', \'53\', \'2\', \'Вежбе\', \'130500\', \'136800\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'139\', \'81\', \'53\', \'6\', \'Предавања\', \'137700\', \'147600\')');
        $this->addSql('INSERT INTO lectures (id, course_id, teacher_id, classroom_id, type, starts_at, ends_at) VALUES (\'140\', \'81\', \'53\', \'4\', \'Вежбе\', \'227700\', \'234000\')');

        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'1\', \'9\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'2\', \'9\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'3\', \'10\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'4\', \'10\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'5\', \'11\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'6\', \'12\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'6\', \'13\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'7\', \'11\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'7\', \'12\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'7\', \'13\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'8\', \'12\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'9\', \'13\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'10\', \'11\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'11\', \'14\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'12\', \'11\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'12\', \'14\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'13\', \'12\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'13\', \'13\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'14\', \'14\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'15\', \'14\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'16\', \'27\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'17\', \'27\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'18\', \'24\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'19\', \'24\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'20\', \'1\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'20\', \'3\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'21\', \'2\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'21\', \'4\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'21\', \'6\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'21\', \'8\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'22\', \'5\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'22\', \'7\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'23\', \'1\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'23\', \'3\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'23\', \'7\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'24\', \'2\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'24\', \'4\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'24\', \'5\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'24\', \'6\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'24\', \'8\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'25\', \'9\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'25\', \'10\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'26\', \'9\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'27\', \'10\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'28\', \'11\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'28\', \'19\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'28\', \'20\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'29\', \'12\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'29\', \'13\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'30\', \'11\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'31\', \'12\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'31\', \'19\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'32\', \'13\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'32\', \'20\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'33\', \'15\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'33\', \'16\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'34\', \'15\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'34\', \'16\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'35\', \'1\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'35\', \'3\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'36\', \'2\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'36\', \'4\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'36\', \'6\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'36\', \'8\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'37\', \'5\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'37\', \'7\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'38\', \'9\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'38\', \'10\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'39\', \'26\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'40\', \'26\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'41\', \'17\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'42\', \'17\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'43\', \'25\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'44\', \'25\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'45\', \'15\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'46\', \'16\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'47\', \'15\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'47\', \'16\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'48\', \'18\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'49\', \'18\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'50\', \'11\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'51\', \'12\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'52\', \'13\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'52\', \'20\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'53\', \'17\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'53\', \'19\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'53\', \'21\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'54\', \'18\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'54\', \'22\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'55\', \'11\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'55\', \'19\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'55\', \'20\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'55\', \'22\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'56\', \'12\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'56\', \'13\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'57\', \'17\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'57\', \'18\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'57\', \'21\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'58\', \'24\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'58\', \'25\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'59\', \'24\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'59\', \'25\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'60\', \'17\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'60\', \'18\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'60\', \'19\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'60\', \'20\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'60\', \'21\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'60\', \'22\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'61\', \'18\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'61\', \'22\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'62\', \'17\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'62\', \'19\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'62\', \'20\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'62\', \'21\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'63\', \'17\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'63\', \'19\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'63\', \'22\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'64\', \'17\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'64\', \'19\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'64\', \'22\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'65\', \'1\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'65\', \'3\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'66\', \'2\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'66\', \'4\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'66\', \'6\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'66\', \'8\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'67\', \'5\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'67\', \'7\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'68\', \'1\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'68\', \'3\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'69\', \'2\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'69\', \'4\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'69\', \'6\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'69\', \'8\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'70\', \'5\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'70\', \'7\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'71\', \'23\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'72\', \'23\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'73\', \'26\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'73\', \'27\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'74\', \'26\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'74\', \'27\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'75\', \'26\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'76\', \'26\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'77\', \'9\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'78\', \'9\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'78\', \'10\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'79\', \'10\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'80\', \'14\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'81\', \'14\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'82\', \'15\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'83\', \'15\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'83\', \'16\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'84\', \'16\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'85\', \'1\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'86\', \'2\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'86\', \'4\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'86\', \'6\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'87\', \'3\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'88\', \'5\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'89\', \'7\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'90\', \'8\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'91\', \'23\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'92\', \'23\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'93\', \'9\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'94\', \'10\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'95\', \'17\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'95\', \'20\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'95\', \'21\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'95\', \'22\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'96\', \'17\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'96\', \'20\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'96\', \'21\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'96\', \'22\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'97\', \'28\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'98\', \'28\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'99\', \'18\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'99\', \'21\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'100\', \'18\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'100\', \'21\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'101\', \'27\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'102\', \'27\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'103\', \'26\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'103\', \'27\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'104\', \'14\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'104\', \'27\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'105\', \'14\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'105\', \'27\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'106\', \'23\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'107\', \'23\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'108\', \'18\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'109\', \'18\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'110\', \'24\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'111\', \'24\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'112\', \'29\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'113\', \'23\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'113\', \'26\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'114\', \'23\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'114\', \'26\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'115\', \'19\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'115\', \'20\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'115\', \'21\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'115\', \'22\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'116\', \'19\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'116\', \'20\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'116\', \'21\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'116\', \'22\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'117\', \'25\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'118\', \'25\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'119\', \'2\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'119\', \'4\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'119\', \'6\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'119\', \'8\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'120\', \'3\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'120\', \'4\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'121\', \'5\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'121\', \'6\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'122\', \'8\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'123\', \'1\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'123\', \'2\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'124\', \'7\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'125\', \'28\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'126\', \'7\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'127\', \'8\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'128\', \'1\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'128\', \'2\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'129\', \'3\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'129\', \'4\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'130\', \'5\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'130\', \'6\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'131\', \'28\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'132\', \'1\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'132\', \'3\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'133\', \'5\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'133\', \'7\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'134\', \'24\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'134\', \'25\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'135\', \'24\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'135\', \'25\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'136\', \'23\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'137\', \'23\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'138\', \'15\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'139\', \'15\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'139\', \'16\')');
        $this->addSql('INSERT INTO classes_lectures (lecture_id, class_id) VALUES (\'140\', \'16\')');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE events CHANGE starts_at starts_at DATETIME NOT NULL, CHANGE ends_at ends_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE lectures CHANGE starts_at starts_at DATETIME NOT NULL, CHANGE ends_at ends_at DATETIME NOT NULL');
    }
}
