<?php

namespace Database\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version20151224145023 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE assistants (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE course_events (id INT NOT NULL, course_id INT DEFAULT NULL, INDEX IDX_FDBF9607591CC992 (course_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE events (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL, disc VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classrooms_events (event_id INT NOT NULL, classroom_id INT NOT NULL, INDEX IDX_8E9C06F871F7E88B (event_id), INDEX IDX_8E9C06F86278D5A8 (classroom_id), PRIMARY KEY(event_id, classroom_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE event_notifications (id INT NOT NULL, event_id INT DEFAULT NULL, INDEX IDX_4459007F71F7E88B (event_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faculties (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, university VARCHAR(255) NOT NULL, wallpaper_path VARCHAR(255) NOT NULL, language VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE feedback (id INT AUTO_INCREMENT NOT NULL, text VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE global_events (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classes (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, year INT NOT NULL, UNIQUE INDEX UNIQ_2ED7EC55E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE class_events (id INT NOT NULL, class_id INT DEFAULT NULL, INDEX IDX_9CDB15F2EA000B10 (class_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classes_lectures (lecture_id INT NOT NULL, class_id INT NOT NULL, INDEX IDX_293D87C935E32FCD (lecture_id), INDEX IDX_293D87C9EA000B10 (class_id), PRIMARY KEY(lecture_id, class_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lecture_notifications (id INT NOT NULL, lecture_id INT DEFAULT NULL, INDEX IDX_BC3C196135E32FCD (lecture_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notifications (id INT AUTO_INCREMENT NOT NULL, description VARCHAR(255) NOT NULL, expires_at DATETIME NOT NULL, disc VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE superUsers (id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teachers (id INT NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE assistants ADD CONSTRAINT FK_EA18B435BF396750 FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_events ADD CONSTRAINT FK_FDBF9607591CC992 FOREIGN KEY (course_id) REFERENCES courses (id)');
        $this->addSql('ALTER TABLE course_events ADD CONSTRAINT FK_FDBF9607BF396750 FOREIGN KEY (id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE classrooms_events ADD CONSTRAINT FK_8E9C06F871F7E88B FOREIGN KEY (event_id) REFERENCES events (id)');
        $this->addSql('ALTER TABLE classrooms_events ADD CONSTRAINT FK_8E9C06F86278D5A8 FOREIGN KEY (classroom_id) REFERENCES classrooms (id)');
        $this->addSql('ALTER TABLE event_notifications ADD CONSTRAINT FK_4459007F71F7E88B FOREIGN KEY (event_id) REFERENCES events (id)');
        $this->addSql('ALTER TABLE event_notifications ADD CONSTRAINT FK_4459007FBF396750 FOREIGN KEY (id) REFERENCES notifications (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE global_events ADD CONSTRAINT FK_BC16421ABF396750 FOREIGN KEY (id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE class_events ADD CONSTRAINT FK_9CDB15F2EA000B10 FOREIGN KEY (class_id) REFERENCES classes (id)');
        $this->addSql('ALTER TABLE class_events ADD CONSTRAINT FK_9CDB15F2BF396750 FOREIGN KEY (id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE classes_lectures ADD CONSTRAINT FK_293D87C935E32FCD FOREIGN KEY (lecture_id) REFERENCES lectures (id)');
        $this->addSql('ALTER TABLE classes_lectures ADD CONSTRAINT FK_293D87C9EA000B10 FOREIGN KEY (class_id) REFERENCES classes (id)');
        $this->addSql('ALTER TABLE lecture_notifications ADD CONSTRAINT FK_BC3C196135E32FCD FOREIGN KEY (lecture_id) REFERENCES lectures (id)');
        $this->addSql('ALTER TABLE lecture_notifications ADD CONSTRAINT FK_BC3C1961BF396750 FOREIGN KEY (id) REFERENCES notifications (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE superUsers ADD CONSTRAINT FK_6494F39FBF396750 FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teachers ADD CONSTRAINT FK_ED071FF6BF396750 FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE classrooms ADD floor INT NOT NULL');
        $this->addSql('DROP INDEX UNIQ_A9A55A4C77153098 ON courses');
        $this->addSql('ALTER TABLE courses ADD name VARCHAR(255) NOT NULL, CHANGE esp espb INT NOT NULL');
        $this->addSql('ALTER TABLE lectures DROP FOREIGN KEY FK_63C861D07D2D84D5');
        $this->addSql('DROP INDEX IDX_63C861D07D2D84D5 ON lectures');
        $this->addSql('ALTER TABLE lectures ADD type VARCHAR(255) NOT NULL, ADD starts_at DATETIME NOT NULL, ADD ends_at DATETIME NOT NULL, CHANGE professor_id teacher_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE lectures ADD CONSTRAINT FK_63C861D041807E1D FOREIGN KEY (teacher_id) REFERENCES teachers (id)');
        $this->addSql('CREATE INDEX IDX_63C861D041807E1D ON lectures (teacher_id)');
        $this->addSql('ALTER TABLE professors DROP first_name, DROP last_name, CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE professors ADD CONSTRAINT FK_2274711EBF396750 FOREIGN KEY (id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX UNIQ_A4698DB2E9CD7668 ON students');
        $this->addSql('ALTER TABLE students CHANGE indexnumber index_number VARCHAR(255) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4698DB28F0EE0A5 ON students (index_number)');
        $this->addSql('ALTER TABLE users ADD organisation_id INT DEFAULT NULL, CHANGE password password VARCHAR(255) DEFAULT NULL, CHANGE register_token register_token VARCHAR(32) DEFAULT NULL, CHANGE register_token_created_at register_token_created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E99E6B1585 FOREIGN KEY (organisation_id) REFERENCES faculties (id)');
        $this->addSql('CREATE INDEX IDX_1483A5E99E6B1585 ON users (organisation_id)');
        $this->addSql('INSERT INTO faculties (id, name, university, wallpaper_path, language) VALUES (\'1\', \'Racunarski fakultet\', \'Union\', \'/settings/default/wallpaper/wallpaper.png\', \'english\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'1\', \'1\', \'Nebojsa\', \'Urosevic\', \'bla\', \'\', \'0000-00-00 00:00:00\', \'nu@gmail.com\', \'$2y$10$/j5GfnQlRqot.QXWraJ8kuw9OaJmJZO4FAWCj6cdRgDhSz93ANjV2\', \'admin\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'2\', \'1\', \'Стеван\', \'Милинковић\', \'\', \'1e0146fbaab13e2f3ee2d75c63a0d55c\', \'2015-12-14 11:33:20\', \'smilinkovic@raf.edu.rs\', \'$2y$10$SmGX/ElmgLZsp9s6dZhpAuxWpBOELNlHGItI4X0DJRKZUt09W4/ci\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'3\', \'1\', \'Наташа\', \'Пржуљ\', \'\', \'8e8faff2ff2105eaca359719b9533f31\', \'2015-12-14 11:35:33\', \'nprzulj@raf.edu.rs\', \'$2y$10$mZJzNWBHtr5nvRhJkVqwOOpQCzfD6Cb2VfLc1cuzvWwxX06a5DxJ.\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'4\', \'1\', \'Кристина\', \'Вушковић\', \'\', \'e3987c0644fe395fa9fc260316b604ec\', \'2015-12-14 11:36:10\', \'kvuskovic@raf.edu.rs\', \'$2y$10$mm9mGAyJ6O7ixdmRcDYgau31bbRFtUxHAN6WiwjqZOKIybAY6.82K\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'5\', \'1\', \'Душан\', \'Тошић\', \'\', \'35af04242327382d5d5a544d3aae3bec\', \'2015-12-14 11:36:37\', \'dtosic@raf.edu.rs\', \'$2y$10$jRDNpfkp7kpD.EfI2qnksuK9vAxpk8B1qzabJZbcY7/58EsyRpr/C\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'6\', \'1\', \'Милан\', \'Видаковић\', \'\', \'2133070a07e3f4707c2eb5618f3b1bb1\', \'2015-12-14 11:37:34\', \'mvidakovic@raf.edu.rs\', \'$2y$10$WVDMkCG1IvAVKNoJf2HeSOpktpeerwlYmZnGssw5rHKT2QauDuNJq\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'7\', \'1\', \'Влајко\', \'Коцић\', \'\', \'39be5c5419a291c5d430b3d4fc6a3194\', \'2015-12-14 11:38:09\', \'kvlajko@raf.edu.rs\', \'$2y$10$XCkdWjGsVqqj9Q0pGD2b5uBafn35nSqirW.bmD0oJVHtTS3xeVhsS\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'8\', \'1\', \'Катарина\', \'Дамњановић\', \'\', \'c6845c0a66ebeb8280258bd448316c73\', \'2015-12-14 11:38:40\', \'katarina.damnjanovic@gmail.com\', \'$2y$10$cph8wcsJA.lSzqoeP4fke.cNFuDZXcIC8.piIKHETGK.00nSTgADi\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'9\', \'1\', \'Ђорђе\', \'Бабић\', \'\', \'48dc8890097cab5e9cc98471212bee03\', \'2015-12-14 11:39:56\', \'djbabic@raf.edu.rs\', \'$2y$10$36L22/GO/m90LdV77AOwsearr1NHjBSFbwMiNUyXJSK30c1/PNIwi\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'10\', \'1\', \'Десимир\', \'Вучић\', \'\', \'87cab626a36ddcbc09d433f3846c34fc\', \'2015-12-14 11:40:23\', \'dvucic@raf.edu.rs\', \'$2y$10$0CFxmEjVkd6NrGF66NeiVOMNa/WDIF1nutssOkD6G56IvoOT2VbT6\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'11\', \'1\', \'Драган\', \'Подлесник\', \'\', \'4569f8b5ec3051a2ef9f6621b96861ae\', \'2015-12-14 11:40:48\', \'dpodlesnik@raf.edu.rs\', \'$2y$10$Bd97T594YW4jJsrhN0yePuF8/2mMh66oHdmYkRGydkMHgYQ8csk0.\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'12\', \'1\', \'Драган\', \'Урошевић\', \'\', \'5a76d209656acd7e3c5a93b8101f458c\', \'2015-12-14 11:41:13\', \'durosevic@raf.edu.rs\', \'$2y$10$YdKa74KCmiMrPQGsAA7H6.oKT2fsN4qbcJCzTpYwwCjUY4fl/f/Le\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'13\', \'1\', \'Бранко\', \'Перишић\', \'\', \'c36ff3d71832aea7ea32a643906b829e\', \'2015-12-14 11:41:47\', \'bperisic@raf.edu.rs\', \'$2y$10$pcQDa3Doq4.J74OBu8ZYBe2JG7FTc3wZx/C7KhFB/0xVjM5ffu1wy\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'14\', \'1\', \'Бојана\', \'Димић-Сурла\', \'\', \'5687c1758b110d5b964ea5dad2ce21bc\', \'2015-12-14 11:42:53\', \'bdimicsurla@raf.edu.rs\', \'$2y$10$75pTbyUqA2Hp31PCCltFEOFVxw6ClgO8vltrmhW/6iGptI4srQDeK\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'15\', \'1\', \'Петар\', \'Станојловић\', \'\', \'9ef6226cc987f5ed40c07e6ba5380c89\', \'2015-12-14 11:44:32\', \'nemamail@gmail.com\', \'$2y$10$ADS0mL6C94Agp6qH6ahyfOpcrQhknJR5r5U8d.Z.p4soDpcdXM.ti\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'16\', \'1\', \'Снежана\', \'Поповић\', \'\', \'5ed95a6c3e045340d8309521cec9a320\', \'2015-12-14 11:44:56\', \'spopovic@raf.edu.rs\', \'$2y$10$q9dE6ZTVg4zVf52J2OYeR.1EgWe6s0GwJIE4oT8V7T0ImkONv0t/G\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'17\', \'1\', \'Драган\', \'Милетић\', \'\', \'0d451876b8e19320a1e4b0e9e42b80be\', \'2015-12-14 11:45:21\', \'dmiletic@raf.edu.rs\', \'$2y$10$iDHZ.L4Ga8HJxAipCIX0yeV5eTrApV8CDzPzb9CNiyrh006L7sIve\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'18\', \'1\', \'Мирјана\', \'Радивојевић\', \'\', \'627d412aff2d79784445e859ab3f404c\', \'2015-12-14 11:45:42\', \'mradivojevic@raf.edu.rs\', \'$2y$10$bWc2L9tfs8lh8N7ISGbMdO.cJl6G1X3bv9zVn.iTnZK.Msz9BqU/u\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'19\', \'1\', \'Мирољуб\', \'Захорјански\', \'\', \'a0eb0b6399648cdb3dbae60a35e615b2\', \'2015-12-14 11:46:09\', \'mzahorjanski@raf.edu.rs\', \'$2y$10$sf0BjVjj1O63b5runicAleN7iXHoCsDptFFoEgAeRypX2ByWH0E3C\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'20\', \'1\', \'Зоран\', \'Фидановски\', \'\', \'c7d3104f4478144292421b0ada11db06\', \'2015-12-14 11:48:08\', \'zfidanovski@raf.edu.rs\', \'$2y$10$uBeysk2ZmcCiTktJ4CB2Tu7CHIU.IQkE.JL9Gf8yEro3qilx7cRFO\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'21\', \'1\', \'Душан\', \'Вујошевић\', \'\', \'269942c3bd7ce9168235bfb872a989a8\', \'2015-12-14 11:48:49\', \'dvujosevic@raf.edu.rs\', \'$2y$10$cqw7Se.o//wzTar29z7w4e54vQ88k1xJQqKW3B0dIm2KzW/TW5/yi\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'22\', \'1\', \'Јелена\', \'Васиљевић\', \'\', \'21e076f15d9f1a98b2e338fb9313ae96\', \'2015-12-14 11:49:14\', \'jvasiljevic@raf.edu.rs\', \'$2y$10$jUDDrFiwXdEMsJGhLclcwu6HxDM3FycNNUi9bAoOPvvWErsAmIIKC\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'23\', \'1\', \'Борислав\', \'Агапиев\', \'\', \'ccef37d49db9ccb5a2d5e137f3bd3d5d\', \'2015-12-14 11:49:35\', \'bagapiev@raf.edu.rs\', \'$2y$10$nGrpZO2zmDDmCWGk6uD45OmRi/0nE2BmFwhVQB1Mv7QQk0Del8JX6\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'24\', \'1\', \'Владимир\', \'Миловановић\', \'\', \'eb0629e35f0d4da7c5a43b65de497ce9\', \'2015-12-14 11:49:57\', \'vmilovanovic@raf.edu.rs\', \'$2y$10$hhFOy7xwn/zZ./aEXmul/.1jJbzC5yv/QCBdy/1.tt2QNauglcd3W\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'25\', \'1\', \'Иван\', \'Елезовић\', \'\', \'27c631f9b0a01bc3f61b9daf51d9b636\', \'2015-12-14 11:50:45\', \'ivanelite3910@hotmail.com\', \'$2y$10$Rp1e1s5P35pRFyaHOzMOaOcjefGjNgFm51qqF5uJo6IG1dHxEJm9i\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'26\', \'1\', \'Стојанка\', \'Бошњак\', \'\', \'ca3279aa8fab4d90b2d082b0dcf67ab9\', \'2015-12-14 11:51:10\', \'nemamail2@gmail.com\', \'$2y$10$ybT.Vq.sDdjEJvi3ywz8Num0XO9Ea8.nnuXfab8tB1DZpjBt6hCra\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'27\', \'1\', \'Ненад\', \'Малешевић\', \'\', \'ff025f44a8b3f7d761e1fbf2d5fd4f11\', \'2015-12-14 11:51:43\', \'malesevicn@yahoo.com\', \'$2y$10$Ub7/hDOhWHJMhOR8DQtSSOEUaK/DbV8zSCABTgZx55q8BaB6QVcBi\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'28\', \'1\', \'Ирина\', \'Бошњак-Перишић\', \'\', \'57b939b9dca9f814470e347d2aad0125\', \'2015-12-14 11:52:09\', \'irinapb@gmail.com\', \'$2y$10$6HK2uZEg1OUrBhq4kEYhceTCG/k3BDp/SOu7V1c2pE2XRfESMOxq6\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'29\', \'1\', \'Звездана\', \'Стојмировић\', \'\', \'d62ca529f7c6ad3899fff6fc9cf4bbe8\', \'2015-12-14 11:52:42\', \'zvezdanas@earthlink.net\', \'$2y$10$xPSZFdkZmQR7VBD1D2NEJ.dCKtM8JQMsXunoEkrn.Esf/GN2/e2Tq\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'30\', \'1\', \'Росана\', \'Теларовић\', \'\', \'d58c6e41eb3dc7712bbb27bbe9ab0348\', \'2015-12-14 11:53:15\', \'rosana@studioromb.com\', \'$2y$10$Im2sb7ELAo27ILhNxoJ5LOUNBHI9/7727MDylLGFFbLuNe1zjGrXG\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'31\', \'1\', \'Вук\', \'Вукићевић\', \'\', \'50c47365f870509e847809469f862e55\', \'2015-12-14 11:53:51\', \'vukicevic7@gmail.com\', \'$2y$10$GN3OL9OJJPl8C0AJtjWrlugOOVtPNgK2Bo7BWHYWh.uhMf5QqFc96\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'32\', \'1\', \'Светлана\', \'Кнежевић\', \'\', \'d741241cc9f219bc5337ca1e553cf731\', \'2015-12-14 11:54:27\', \'nemamail3@gmail.com\', \'$2y$10$SuzeRalpFSv4OzXbYLnENOD3AwQdp/3P3Rp7iIFnjNS7FEDYhqBJ6\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'33\', \'1\', \'Милан\', \'Ђурић\', \'\', \'3facaa208786feda7a4ab335c9747628\', \'2015-12-14 11:55:00\', \'maxpenguine@gmail.com\', \'$2y$10$T9336KBOPqezgWdmRZeGXeq/extXhDIAZWkCpIAm8dwIP51zmDze2\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'34\', \'1\', \'Младен\', \'Станојевић\', \'\', \'f2cbb55f332e8c750444c10a5e84dbeb\', \'2015-12-14 11:55:24\', \'mladen.stanojevic@pupin.rs\', \'$2y$10$pzxopcEqAoFudOZovy26lOR8J3px3uuRUTmMFxhcbcwob8a8lvPse\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'35\', \'1\', \'Ирена\', \'Јовановић\', \'\', \'52af7312eb25f1291010ada79876993b\', \'2015-12-14 11:55:48\', \'ijovanovic@raf.edu.rs\', \'$2y$10$7wuLScbFxCTXDpwjaCUWDeHeHEfRTyp4hEGIQFYvEj.Lnuxn6b0Aa\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'36\', \'1\', \'Миланка\', \'Гардашевић-Филиповић\', \'\', \'6a5b6f4b636998d180df40f8020180db\', \'2015-12-14 11:56:17\', \'mgardasevic@raf.edu.rs\', \'$2y$10$ZEH0PpciXDwNGI6RLAxhR.2IFkDlqDEmAJVxIKho5mWGh7iTY/vkK\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'37\', \'1\', \'Милош\', \'Јовановић\', \'\', \'ebd1adb7b6d9e6014892f304a8c3fae3\', \'2015-12-14 11:56:46\', \'mjovanovic@raf.edu.rs\', \'$2y$10$PFeA/I3RFfLrqV2vyNtHEe1SsoPJuAQ5feoW92zuzUFN.7FeJZm/C\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'38\', \'1\', \'Бранка\', \'Јокановић\', \'\', \'b9ec3d1aa6fbab390574ecd656468904\', \'2015-12-14 12:33:47\', \'branka.jokanovic@ipb.ac.rs\', \'$2y$10$UEoZfgvMttWzz7b/TFywSuMEGPLeK91kcqeTopTtTj1upV9r1r4Jm\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'39\', \'1\', \'Небојша\', \'Ромчевић\', \'\', \'defdc4f719e154c49ff1204cea847635\', \'2015-12-14 12:34:13\', \'nebojsa.romcevic@ipb.ac.rs\', \'$2y$10$gE6JtoOoLCQwLI0unVfzk.A0gZ9WQU4lXEFmKMqDlJk0Lv26NfNoa\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'40\', \'1\', \'Ненад\', \'Младеновић\', \'\', \'25239e80223e8983198e9ca7a116f18b\', \'2015-12-14 12:34:48\', \'Nenad.Mladenovic@brunel.ac.uk\', \'$2y$10$DeEG1GqcRBZoRGac/9v4IOHkgT1R5g1.On0GiVSzJQe3zKh5UvYoO\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'41\', \'1\', \'Слободан\', \'Симић\', \'\', \'f6c11ab0c5228f17247c82ff1549841d\', \'2015-12-14 12:35:12\', \'sksimic@mi.sanu.ac.rs\', \'$2y$10$NJiQBPwYm4HV6U2OeJy24.Gtb8.tH9gqUHBBPI1uBBwiDdXkF9lN6\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'42\', \'1\', \'Душанка\', \'Стојановић\', \'\', \'adc3c7af5568a45cca5c3eb0917a1e03\', \'2015-12-14 12:35:53\', \'dusanka.stojanovic@ipb.ac.rs\', \'$2y$10$sVbZDxdnapm85dxSWyedJeRKiEUcGZ9sYNr2SrgQnqCAndD7lGKWS\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'43\', \'1\', \'Дејан\', \'Тимотијевић\', \'\', \'1d75097279ae06bee39edd550a6c9226\', \'2015-12-14 12:36:26\', \'dejan.timotijevic@ipb.ac.rs\', \'$2y$10$mF8LVKtdr4iPuyjrlUhX5ebATOVcbP6UTloC8F5s0UE4Qmg8nQBS.\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'44\', \'1\', \'Јелена\', \'Трајић\', \'\', \'e3bd73820d29531e2f20bfacc1017bef\', \'2015-12-14 12:36:49\', \'jelena.trajic@ipb.ac.rs\', \'$2y$10$ivQVrDT1BtgUDnwBiQkm2.euw8MSkZuSCgRbWvJk3Nw69B6D/lXGC\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'45\', \'1\', \'Татјана\', \'Давидовић\', \'\', \'081c7f431080ca1c30d7f7e34c5a354e\', \'2015-12-14 12:37:15\', \'tanjad@mi.sanu.ac.rs\', \'$2y$10$.3rhOhdrSHBK0SUuicMakOM3J60N0Sppjr3GkFytADVEo7CsTuRPW\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'46\', \'1\', \'Мирјана\', \'Марковић\', \'\', \'f587d2fbbd14f107cf681d1fca546bb1\', \'2015-12-14 12:37:52\', \'mmarkovic@raf.edu.rs\', \'$2y$10$eLxaNYqTjADrI5rz2FtyjuPVRxU3snowauW07x7G9QdOm.KlWxAn6\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'47\', \'1\', \'Иван\', \'Бабовић\', \'\', \'d7c8fea4e94be5c440eff52bb2c094de\', \'2015-12-14 12:38:32\', \'ibabovic@raf.edu.rs\', \'$2y$10$1zIqZqJEgZ3HJ9xQoZm9eeqemkzCDOEzKFg74umWlCiLXzp5WCsHK\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'48\', \'1\', \'Драган\', \'Стојановић\', \'\', \'c087b250e7701aab2fb08b277da26ba8\', \'2015-12-14 12:38:55\', \'dstojanovic@raf.edu.rs\', \'$2y$10$CVTULiE./4tfx5t4cWJkPu/Lr/ATnwkjukOdZJ7x.cEwkBca9SGlS\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'50\', \'1\', \'Јована\', \'Ристић\', \'\', \'d2093171addd96776ac85362ce66115a\', \'2015-12-14 12:40:27\', \'jristic@raf.edu.rs\', \'$2y$10$JmxQjGReEnc9hHx3Vcvb7.gygXYTc.PO6wWxwR4dLEuzwwpzMU0cC\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'51\', \'1\', \'Немања\', \'Радосављевић\', \'\', \'54bb577b2532fd104b0b454a2ed0a156\', \'2015-12-14 12:41:45\', \'nradosavljevic@raf.edu.rs\', \'$2y$10$D/FoolRA9sL5oAq0dMq.x.uGQ8sbM4S274XXpfQqIJY2BK9NglcSK\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'52\', \'1\', \'Петар\', \'Бојовић\', \'\', \'1d20bdbb000a6153390cf0f30844667f\', \'2015-12-14 12:42:10\', \'petar.bojovic@paxy.in.rs\', \'$2y$10$vIwjfiislq9jyfYRXn6.YeW/jzq/eyUBcS71KyRH3gUJsZIBpOfK6\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'53\', \'1\', \'Бранислав\', \'Милојковић\', \'\', \'faef8c91c82cd360fbe1cee15c162351\', \'2015-12-14 12:42:33\', \'bmilojkovic@raf.edu.rs\', \'$2y$10$voLddcByomKcBzKHXydu4uzyZp1C.77i1xT61k7UQYQRzATVXCnzG\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'54\', \'1\', \'Милан\', \'Шкарић\', \'\', \'1573af50fd58573f454478e2bce3962a\', \'2015-12-14 12:42:56\', \'milan.skaric@gmail.com\', \'$2y$10$Ud06Uv7e.F1im.eIZ/o37.rmu9YSKjGPr1T1f.9apOUgoXor8eeaW\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'55\', \'1\', \'Селена\', \'Вукотић\', \'\', \'4b788b53c4f10d0286aa8cde2b80548b\', \'2015-12-14 12:43:18\', \'selena.vukotic@gmail.com\', \'$2y$10$B.qX9gCEoQDZ18rfg2DQNOKeDnvHCPT3eQWH9hI6fZFcPJQYY4s4q\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'56\', \'1\', \'Далибор\', \'Ристић\', \'\', \'d6569d682cb4fc60bd070be67f947f51\', \'2015-12-14 12:43:43\', \'dristic@raf.edu.rs\', \'$2y$10$8r5FzqVA/0s5k6W.30Q.Re5nZSeR/36lpX5CvIQAhwA0ObL2SAQ2i\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'57\', \'1\', \'Игор\', \'Зечевић\', \'\', \'d3c2221b0217f951bdc68448d2a60e21\', \'2015-12-14 12:44:14\', \'izecevic@raf.edu.rs\', \'$2y$10$PD9iajr8o3fDV0FICJvPYekJXgGDFTmMA.Q.spZneZHvEJijaO/Ge\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'58\', \'1\', \'Мерсиха\', \'Прушевић-Дулић\', \'\', \'fce218bebddd4537191d65e742add8b5\', \'2015-12-14 12:44:43\', \'mersihaprusho@yahoo.com\', \'$2y$10$SYgLe2ekmsuVsHzdyqkG.OuiOBzLPpGzTUGz2a79aAKcjr/z2oWgm\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'59\', \'1\', \'Јелена\', \'Келеува\', \'\', \'1120b9a52a2a8f541745157db3adf5b6\', \'2015-12-14 12:45:31\', \'jelena.keleuva@gmail.com\', \'$2y$10$IlCmGxWnbH8MMN4cWCA2COuJv8zKeK9LlHKFfZffWRRqzbcnlXJlq\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'60\', \'1\', \'Марија\', \'Јеротијевић\', \'\', \'65f9185ada87e41b9c2dfb614a1cf7d1\', \'2015-12-14 12:45:54\', \'mjerotijevic@raf.edu.rs\', \'$2y$10$rZARN8cONYMNc7hBxwuJuuEngSVC3B5SX4mgz4bNIp2.5Zc7hXSzW\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'61\', \'1\', \'Владимир\', \'Бошковић\', \'\', \'96e484da22c45ea476d13210b9ef3503\', \'2015-12-14 12:47:52\', \'vboskovic@raf.edu.rs\', \'$2y$10$zVzc8CScEYVrusdvAXGj5u2S3Ld4URU0VMEdD4VgGjwrPaoUh9hSe\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'62\', \'1\', \'Синиша\', \'Лале\', \'\', \'abc95bd851f9dc44e8df40fa77f979ec\', \'2015-12-14 12:48:19\', \'lalas@gmx.com\', \'$2y$10$NmYGWOW53JAhorKHpHu7A.vqhU4imkKj9Y.f8Jehy3rrRyy7ouELy\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'63\', \'1\', \'Милан\', \'Томић\', \'\', \'d7cb722e55df24037ee7da089f687186\', \'2015-12-14 12:48:38\', \'mtomic@raf.edu.rs\', \'$2y$10$244xHfj.tSrbky4ip.n3le5eh/4UtuM6qFMS8jU6If1oKNuru3SYq\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'64\', \'1\', \'Александар\', \'Станчић\', \'\', \'47c8d0ff0b3b2f1dc3c5ec267f2c029e\', \'2015-12-14 12:49:10\', \'nemamail4@gmail.com\', \'$2y$10$gBq4VOxpuT9Ecd58NeweR.2pURPGPSEWrunqk2KCdg1yJ2/TphITK\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'65\', \'1\', \'Дуња\', \'Мајсторовић\', \'\', \'fd896191a981cf760f3ce3b394f80e33\', \'2015-12-14 12:49:46\', \'dmajstorovic@raf.edu.rs\', \'$2y$10$muPaD5Q1UuOCFj8GdAQFp.M0ObDEdMuVaD3l4HMP07DCB24SeKcFq\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'66\', \'1\', \'Лазар\', \'Миленковић\', \'\', \'ac3d490e9f5af857c1314fb7e5937f68\', \'2015-12-14 22:20:24\', \'faker@gmail.com\', \'$2y$10$EsKp6x4a/drsp3Qet318LuqWUPBZZHbXf3tjQEl3yZCECImAQhB2u\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'67\', \'1\', \'Братислав\', \'Димитров\', \'\', \'91230cea77f69095157161b11cb41b01\', \'2015-12-14 22:35:41\', \'faker2@gmail.com\', \'$2y$10$vFsCj2Xw8mDa4XA7/y/AtebSzJ4cHvesw.2IlUqZWSMM9QUe6Tsxe\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'68\', \'1\', \'Слађан\', \'Кантар\', \'\', \'90b41785d388e103d910492909e09db9\', \'2015-12-15 11:55:52\', \'faker3@gmail.com\', \'$2y$10$fuK5bt5EUk6V5PRUzgMOzu/Km/clF3OPKLVtu.u6nN.4gCjJbK7qC\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'69\', \'1\', \'Петар\', \'Првуловић\', \'\', \'3d84644f97d94524d72228cd1649a0fd\', \'2015-12-15 12:01:59\', \'faker4@gmail.com\', \'$2y$10$lYUGaKfdfhDrs0YlqJbwe.oO1hJfOnfjJswKkLvszhEbKc1XMPwW.\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'70\', \'1\', \'Вера\', \'Врбица-Матејић\', \'\', \'4aefe329cf507eb9d89cf03007219884\', \'2015-12-15 14:20:37\', \'faker5@gmail.com\', \'$2y$10$gLpJpDcV8rxbzlV60b1J/uq94aYd3lYiMy4TQflYaJ6cOUnQVV9lW\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'71\', \'1\', \'Димитрије\', \'Димић\', \'\', \'e86e07451915ca339a30a5fac665ef10\', \'2015-12-15 14:27:58\', \'faker6@gmail.com\', \'$2y$10$cWlZjaL4kERS5piZFmwSz.OaVouhtJfGK.lh7vxuLUWG.dq934fsa\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'72\', \'1\', \'Александар\', \'Ивановић\', \'\', \'8c10563038bcd2e620e36af1b60979cb\', \'2015-12-15 14:30:29\', \'faker7@gmail.com\', \'$2y$10$d3wtJnT63cj7ZXmIJSujSumORYYuqh5vGewYcU3Va7yG1PR9iNknO\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'73\', \'1\', \'Дејан\', \'Максимовић\', \'\', \'a0b5d7e4b189a3d3197335a6ed98c5bb\', \'2015-12-15 14:32:05\', \'faker8@gmail.com\', \'$2y$10$vSLB.nxRbPsnSM8d2MT0ge50jvjABEZo0sd5R8lXS7TL5cVTg.pNO\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'74\', \'1\', \'Миланка\', \'Филиповић\', \'\', \'90a8691eec23ae4df60ff72123a09914\', \'2015-12-15 14:37:47\', \'faker9@gmail.com\', \'$2y$10$oTIZMz/R/Rom9icl7PibC.x2KIyoCWrDlRyE1d7j8mQquExH9Ld1O\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'75\', \'1\', \'Игор\', \'Мијатовић\', \'\', \'ed01dec2a9dc4b1592d17cb49b47dc20\', \'2015-12-15 14:45:50\', \'faker10@gmail.com\', \'$2y$10$tEnb2Odqe5W63wrpjcWWouA5tumLrIw0.eBJQEVc25IyGeeSv0l3q\', \'assistant\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'77\', \'1\', \'Горан\', \'Мартић\', \'\', \'337ed95e916a573abfedd611e26dcf98\', \'2015-12-15 15:00:31\', \'faker12@gmail.com\', \'$2y$10$/m4SSKQ/DtlhcYDFlcSTEezywTsX0oMyuoWaX6eBchZ8AX2Of9WC2\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'78\', \'1\', \'Милош\', \'Раденковић\', \'\', \'08e3c3949b30969ea7180df394e8f38e\', \'2015-12-15 15:02:17\', \'faker13@gmail.com\', \'$2y$10$YS/IOrXsYg.L1xKsKpntJujIZCYEDm.CQaBJuqf7iDxUAwjUbMa.K\', \'professor\')');
        $this->addSql('INSERT INTO users (id, organisation_id, first_name, last_name, remember_token, register_token, register_token_created_at, email, password, disc) VALUES (\'79\', \'1\', \'Душан\', \'Здравковић\', \'\', \'6ef5a5d1bf01f0e1d27f325da8f02bc7\', \'2015-12-15 15:03:58\', \'faker14@gmail.com\', \'$2y$10$ZfdFvJMxW27VzTx.MwrCkuwi/nWeWPLIzCjGNGsyLap.8E8rMR3w.\', \'assistant\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'2\', \'редован професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'3\', \'редован професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'4\', \'редован професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'5\', \'редован професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'6\', \'редован професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'7\', \'редован професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'8\', \'редован професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'9\', \'ванредни професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'10\', \'ванредни професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'11\', \'ванредни професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'12\', \'ванредни професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'13\', \'ванредни професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'14\', \'ванредни професор\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'15\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'16\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'17\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'18\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'19\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'20\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'21\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'22\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'23\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'24\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'25\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'26\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'27\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'28\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'29\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'30\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'31\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'32\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'33\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'34\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'35\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'36\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'37\', \'доцент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'38\', \'научни саветник\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'39\', \'научни саветник\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'40\', \'научни саветник\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'41\', \'научни саветник\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'42\', \'виши научни сарадник\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'43\', \'виши научни сарадник\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'44\', \'виши научни сарадник\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'45\', \'виши научни сарадник\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'46\', \'професор струковних студија\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'47\', \'предавач струковних студија\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'48\', \'предавач струковних студија\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'50\', \'наставник вештина - предавач\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'51\', \'aсистент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'52\', \'aсистент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'53\', \'aсистент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'54\', \'aсистент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'55\', \'aсистент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'56\', \'aсистент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'57\', \'aсистент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'58\', \'aсистент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'59\', \'aсистент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'60\', \'aсистент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'61\', \'сарадник у настави\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'62\', \'сарадник у настави\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'63\', \'сарадник у настави\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'64\', \'сарадник у настави\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'65\', \'сарадник у настави\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'66\', \'студент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'67\', \'faker\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'68\', \'студент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'69\', \'студент\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'70\', \'faker\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'71\', \'faker\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'72\', \'faker\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'73\', \'faker\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'74\', \'faker\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'75\', \'faker\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'77\', \'faker\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'78\', \'faker\')');
        $this->addSql('INSERT INTO teachers (id, title) VALUES (\'79\', \'faker\')');
        $this->addSql('INSERT INTO admins (id) VALUES (\'1\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'51\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'52\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'53\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'54\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'55\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'56\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'57\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'58\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'59\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'60\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'61\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'62\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'63\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'64\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'65\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'66\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'68\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'69\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'71\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'72\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'73\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'75\')');
        $this->addSql('INSERT INTO assistants (id) VALUES (\'79\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'2\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'3\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'4\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'5\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'6\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'7\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'8\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'9\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'10\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'11\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'12\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'13\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'14\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'15\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'16\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'17\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'18\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'19\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'20\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'21\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'22\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'23\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'24\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'25\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'26\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'27\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'28\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'29\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'30\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'31\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'32\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'33\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'34\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'35\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'36\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'37\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'38\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'39\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'40\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'41\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'42\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'43\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'44\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'45\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'46\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'47\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'48\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'50\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'67\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'70\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'74\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'77\')');
        $this->addSql('INSERT INTO professors (id) VALUES (\'78\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'1\', \'101\', \'1\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'2\', \'102\', \'1\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'3\', \'103\', \'1\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'4\', \'104\', \'1\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'5\', \'105\', \'1\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'6\', \'106\', \'1\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'7\', \'107\', \'1\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'8\', \'108\', \'1\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'9\', \'1с1\', \'1\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'10\', \'1с2\', \'1\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'11\', \'201\', \'2\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'12\', \'202\', \'2\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'13\', \'203\', \'2\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'14\', \'206\', \'2\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'15\', \'2с1\', \'2\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'16\', \'2с2\', \'2\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'17\', \'301\', \'3\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'18\', \'302\', \'3\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'19\', \'304\', \'3\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'20\', \'305\', \'3\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'21\', \'307\', \'3\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'22\', \'308\', \'3\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'23\', \'310\', \'3\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'24\', \'3с1\', \'3\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'25\', \'3с2\', \'3\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'26\', \'401\', \'4\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'27\', \'402\', \'4\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'28\', \'поновци\', \'0\')');
        $this->addSql('INSERT INTO classes (id, name, year) VALUES (\'29\', \'Такмичари\', \'0\')');
        $this->addSql('INSERT INTO classrooms (id, name, directions, floor) VALUES (\'1\', \'Учионица 1\', \'\', \'6\')');
        $this->addSql('INSERT INTO classrooms (id, name, directions, floor) VALUES (\'2\', \'Учионица 2\', \'\', \'6\')');
        $this->addSql('INSERT INTO classrooms (id, name, directions, floor) VALUES (\'3\', \'Учионица 3\', \'\', \'6\')');
        $this->addSql('INSERT INTO classrooms (id, name, directions, floor) VALUES (\'4\', \'Учионица 4\', \'\', \'6\')');
        $this->addSql('INSERT INTO classrooms (id, name, directions, floor) VALUES (\'5\', \'Учионица 5\', \'\', \'6\')');
        $this->addSql('INSERT INTO classrooms (id, name, directions, floor) VALUES (\'6\', \'Учионица 6\', \'\', \'6\')');
        $this->addSql('INSERT INTO classrooms (id, name, directions, floor) VALUES (\'7\', \'Професорски кабинет\', \'\', \'6\')');
        $this->addSql('INSERT INTO classrooms (id, name, directions, floor) VALUES (\'8\', \'Асистентска соба\', \'\', \'6\')');
        $this->addSql('INSERT INTO classrooms (id, name, directions, floor) VALUES (\'9\', \'РГ 3\', \'\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'1\', \'Линеарна алгебра и аналитичка геометрија\', \'\', \'8\', \'1\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'2\', \'Дискретне структуре\', \'\', \'8\', \'1\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'3\', \'Увод у програмирање\', \'\', \'8\', \'1\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'4\', \'Енглески 1\', \'\', \'3\', \'1\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'5\', \'Пословне апликације\', \'\', \'3\', \'1\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'6\', \'Математичка анализа\', \'\', \'8\', \'2\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'7\', \'Објектно-оријентисано програмирање\', \'\', \'8\', \'2\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'8\', \'Основи рачунарских система\', \'\', \'8\', \'2\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'9\', \'Енглески 2\', \'\', \'3\', \'2\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'10\', \'Писмено и усмено изражавање\', \'\', \'3\', \'2\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'11\', \'Алгоритми и структуре података\', \'\', \'8\', \'3\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'12\', \'Дизајн софтвера\', \'\', \'8\', \'3\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'13\', \'Интелигентни системи\', \'\', \'8\', \'3\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'14\', \'Алгебра\', \'\', \'6\', \'3\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'15\', \'Оперативни системи\', \'\', \'8\', \'4\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'16\', \'Рачунарске мреже\', \'\', \'8\', \'4\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'17\', \'Управљање информацијама\', \'\', \'8\', \'4\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'18\', \'Дизајн и анализа алгоритама\', \'\', \'6\', \'4\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'19\', \'Програмски преводиоци\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'20\', \'Рачунарска графика\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'21\', \'Геометријски алгоритми\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'22\', \'Симболичко рачунање\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'23\', \'Софтверске компоненте\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'24\', \'Криптографија\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'25\', \'Системи у реалном времену\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'26\', \'Препознавање говора\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'27\', \'Паралелни алгоритми\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'28\', \'Вероватноћа и статистика\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'29\', \'Интеракција човек-рачунар\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'30\', \'Web програмирање\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'31\', \'Генетски алгоритми\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'32\', \'Моделовање и симулација\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'33\', \'Функционално програмирање\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'34\', \'Скрипт језици\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'35\', \'Неуралне мреже\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'36\', \'Комбинаторика и теорија графова\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'37\', \'Управљање пројектима\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'38\', \'Фази логика\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'39\', \'Интегрисани информациони системи\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'40\', \'Складишта података\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'41\', \'Мултимедијални информациони системи\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'42\', \'Тестирање софтвера\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'43\', \'Напредно Јава програмирање\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'44\', \'Теорија алгоритама, аутомата и језика\', \'\', \'8\', \'8\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'45\', \'Софтверско инжењерство\', \'\', \'9\', \'8\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'46\', \'Конкурентни и дистрибуирани системи\', \'\', \'7\', \'8\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'47\', \'Основи електронике\', \'\', \'8\', \'3\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'48\', \'Напредна математичка анализа\', \'\', \'6\', \'3\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'49\', \'Сигнали и системи\', \'\', \'8\', \'3\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'50\', \'Архитектура рачунара\', \'\', \'6\', \'4\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'51\', \'Дигиталне комуникације\', \'\', \'8\', \'4\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'52\', \'Кодовање и теорија информација\', \'\', \'8\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'53\', \'Дигитална електроника\', \'\', \'5\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'54\', \'Пројектовање рачунарских система\', \'\', \'5\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'55\', \'Рачунарске мреже великих система\', \'\', \'5\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'56\', \'Системско програмирање\', \'\', \'5\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'57\', \'Физичка електроника\', \'\', \'5\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'58\', \'Практичне технике рутирања\', \'\', \'5\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'59\', \'Компресија података\', \'\', \'7\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'60\', \'Електромагнетика\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'61\', \'Управљачки системи\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'62\', \'Безбедност мрежа\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'63\', \'Увод у роботику\', \'\', \'6\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'64\', \'Бежичне и мобилне комуникације\', \'\', \'7\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'65\', \'Сигурни и критични системи\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'66\', \'Сензори и актуатори\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'67\', \'Скалабилне рачунарске мреже\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'68\', \'Вишеслојне комутиране рачунарске мреже\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'69\', \'Мреже за удаљени приступ\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'70\', \'Системи на чипу\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'71\', \'Дигитална обрада сигнала\', \'\', \'7\', \'8\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'72\', \'Наменски рачунарски системи\', \'\', \'7\', \'8\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'73\', \'Администрација и одржавање система 1\', \'\', \'8\', \'1\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'74\', \'Основи информационих технологија\', \'\', \'8\', \'1\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'75\', \'Организација рачунара\', \'\', \'8\', \'1\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'76\', \'Практикум из архитектуре рачунара и оперативних система\', \'\', \'3\', \'1\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'77\', \'Администрација и одржавање система 2\', \'\', \'8\', \'2\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'78\', \'Дизајн и развој web страна\', \'\', \'8\', \'2\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'79\', \'Пословни софтвер\', \'\', \'8\', \'2\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'80\', \'Основи програмирања\', \'\', \'8\', \'3\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'81\', \'Web системи и технологија\', \'\', \'8\', \'3\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'82\', \'Информациони системи\', \'\', \'8\', \'3\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'83\', \'Енглески 3\', \'\', \'6\', \'3\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'84\', \'Рачунарске комуникације\', \'\', \'8\', \'4\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'85\', \'Програмирање wеб апликација\', \'\', \'8\', \'4\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'86\', \'Електронско пословање\', \'\', \'8\', \'4\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'87\', \'Увод у софтверско инжењерство\', \'\', \'8\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'88\', \'ИТ сервис менаџмент\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'89\', \'Управљање и одржавање Windows Server окружења\', \'\', \'8\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'90\', \'Имплементирање Microsoft ISA сервера\', \'\', \'8\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'91\', \'SQL програмирање\', \'\', \'8\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'92\', \'C# програмирање\', \'\', \'8\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'93\', \'Историја рачунарства\', \'\', \'4\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'94\', \'Увод у администрацију IP мрежа\', \'\', \'8\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'95\', \'Конфигурација и одржавање IP мрежа\', \'\', \'8\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'96\', \'Практичне технике заштите у IP мрежама\', \'\', \'8\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'97\', \'Развој апликација у облаку\', \'\', \'8\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'98\', \'Развој wеб апликација и сервиса\', \'\', \'8\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'99\', \'Microsoft технологије за приступ подацима\', \'\', \'8\', \'6\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'100\', \'Пројектовање база података\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'101\', \'Имплементација MS internet security\', \'\', \'8\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'102\', \'Кодовање и теорија информацијама\', \'\', \'6\', \'5\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'103\', \'Такмичари\', \'\', \'0\', \'0\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'104\', \'Рачунарство и друштво\', \'\', \'3\', \'8\')');
        $this->addSql('INSERT INTO courses (id, name, code, espb, semester) VALUES (\'105\', \'Теорија алгоритама аутомата и језика\', \'\', \'6\', \'7\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'1\', \'Испитни рок\', \'Јануарски испитни рок\', \'2016-01-21 00:00:00\', \'2016-02-10 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'2\', \'Испитни рок\', \'Фебруарски испитни рок\', \'2016-02-11 00:00:00\', \'2016-02-28 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'3\', \'Испитни рок\', \'Јунски испитни рок\', \'2016-06-10 00:00:00\', \'2016-06-30 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'4\', \'Испитни рок\', \'Јулски испитни рок\', \'2016-07-01 00:00:00\', \'2016-07-14 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'5\', \'Испитни рок\', \'Септембарски испитни рок\', \'2016-08-22 00:00:00\', \'2016-09-04 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'6\', \'Испитни рок\', \'Окртобарски испитни рок\', \'2016-09-05 00:00:00\', \'2016-09-15 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'7\', \'Испитни рок\', \'Окртобарски испитни рок 2\', \'2016-09-16 00:00:00\', \'2016-09-26 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'8\', \'Колоквијумска недеља\', \'I колоквијумска недеља\', \'2015-11-21 00:00:00\', \'2015-11-29 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'9\', \'Колоквијумска недеља\', \'II колоквијумска недеља\', \'2016-01-13 00:00:00\', \'2016-01-20 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'10\', \'Колоквијумска недеља\', \'III колоквијумска недеља\', \'2016-04-16 00:00:00\', \'2016-04-24 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'11\', \'Колоквијумска недеља\', \'IV колоквијумска недеља\', \'2016-06-02 00:00:00\', \'2016-06-09 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'12\', \'Плаћање школарине\', \'I рата\', \'2015-10-01 00:00:00\', \'2015-10-01 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'13\', \'Плаћање школарине\', \'II рата\', \'2015-12-31 00:00:00\', \'2015-12-31 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'14\', \'Плаћање школарине\', \'II рата\', \'2016-04-01 00:00:00\', \'2016-04-01 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'15\', \'Нерадни дани\', \'Празник\', \'2015-11-11 00:00:00\', \'2015-11-11 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'16\', \'Нерадни дани\', \'Празник\', \'2016-01-01 00:00:00\', \'2016-01-02 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'17\', \'Нерадни дани\', \'Празник\', \'2016-01-07 00:00:00\', \'2016-01-07 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'18\', \'Нерадни дани\', \'Празник\', \'2016-02-15 00:00:00\', \'2016-02-16 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'19\', \'Нерадни дани\', \'Празник\', \'2016-04-29 00:00:00\', \'2016-05-03 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO events (id, type, description, starts_at, ends_at, disc) VALUES (\'20\', \'Нерадни дани\', \'Raspust\', \'2016-07-15 00:00:00\', \'2016-08-21 00:23:59\', \'global_event\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'1\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'2\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'3\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'4\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'5\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'6\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'7\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'8\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'9\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'10\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'11\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'12\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'13\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'14\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'15\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'16\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'17\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'18\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'19\')');
        $this->addSql('INSERT INTO global_events (id) VALUES (\'20\')');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE course_events DROP FOREIGN KEY FK_FDBF9607BF396750');
        $this->addSql('ALTER TABLE classrooms_events DROP FOREIGN KEY FK_8E9C06F871F7E88B');
        $this->addSql('ALTER TABLE event_notifications DROP FOREIGN KEY FK_4459007F71F7E88B');
        $this->addSql('ALTER TABLE global_events DROP FOREIGN KEY FK_BC16421ABF396750');
        $this->addSql('ALTER TABLE class_events DROP FOREIGN KEY FK_9CDB15F2BF396750');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E99E6B1585');
        $this->addSql('ALTER TABLE class_events DROP FOREIGN KEY FK_9CDB15F2EA000B10');
        $this->addSql('ALTER TABLE classes_lectures DROP FOREIGN KEY FK_293D87C9EA000B10');
        $this->addSql('ALTER TABLE event_notifications DROP FOREIGN KEY FK_4459007FBF396750');
        $this->addSql('ALTER TABLE lecture_notifications DROP FOREIGN KEY FK_BC3C1961BF396750');
        $this->addSql('ALTER TABLE lectures DROP FOREIGN KEY FK_63C861D041807E1D');
        $this->addSql('DROP TABLE assistants');
        $this->addSql('DROP TABLE course_events');
        $this->addSql('DROP TABLE events');
        $this->addSql('DROP TABLE classrooms_events');
        $this->addSql('DROP TABLE event_notifications');
        $this->addSql('DROP TABLE faculties');
        $this->addSql('DROP TABLE feedback');
        $this->addSql('DROP TABLE global_events');
        $this->addSql('DROP TABLE classes');
        $this->addSql('DROP TABLE class_events');
        $this->addSql('DROP TABLE classes_lectures');
        $this->addSql('DROP TABLE lecture_notifications');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE superUsers');
        $this->addSql('DROP TABLE teachers');
        $this->addSql('ALTER TABLE classrooms DROP floor');
        $this->addSql('ALTER TABLE courses DROP name, CHANGE espb esp INT NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A9A55A4C77153098 ON courses (code)');
        $this->addSql('DROP INDEX IDX_63C861D041807E1D ON lectures');
        $this->addSql('ALTER TABLE lectures DROP type, DROP starts_at, DROP ends_at, CHANGE teacher_id professor_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE lectures ADD CONSTRAINT FK_63C861D07D2D84D5 FOREIGN KEY (professor_id) REFERENCES professors (id)');
        $this->addSql('CREATE INDEX IDX_63C861D07D2D84D5 ON lectures (professor_id)');
        $this->addSql('ALTER TABLE professors DROP FOREIGN KEY FK_2274711EBF396750');
        $this->addSql('ALTER TABLE professors ADD first_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, ADD last_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('DROP INDEX UNIQ_A4698DB28F0EE0A5 ON students');
        $this->addSql('ALTER TABLE students CHANGE index_number indexNumber VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4698DB2E9CD7668 ON students (indexNumber)');
        $this->addSql('DROP INDEX IDX_1483A5E99E6B1585 ON users');
        $this->addSql('ALTER TABLE users DROP organisation_id, CHANGE register_token register_token VARCHAR(32) NOT NULL COLLATE utf8_unicode_ci, CHANGE register_token_created_at register_token_created_at VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, CHANGE password password VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci');
    }
}
